# site settings
title: triangle
subtitle: by HTML5 
email: contactmaroofsha@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/triangle" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555



# social settings
500px_url:
facebook_url:
github_url: https://Theclaypotcook.github.io
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/maroofshasoaps
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/maroofsha2012

# build settings
markdown: kramdown

sass:
  style: compressed
